---
- name: Mount file system with UUID
  hosts: all
  become: true
  
  vars:
    mount_point: "/mnt/drive"
    device_uuid: ""
    directory_path: "/data/mydir"
    directory_owner: "myuser"
    directory_group: "mygroup"
    directory_mode: "0770"
    
    tasks:
    - name: Create mount point
      file:
        path: "{{ mount_point }}"
        state: directory
        
    - name: Get device path from UUID
      shell: blkid -U {{ device_uuid }}
      register: blkid_output
      
    - name: Mount file system
      mount:
        path: "{{ mount_point }}"
        state: mounted
    
    notify:
     - restart_service
      
    roles:
      - createdir 