---
- name: Create Samba Writable Directory
  hosts: all
  become: true
  
  vars:
    samba_share_name: "myshare"
    samba_share_path: "/data/fontos"
    samba_share_guest_ok: "yes"
    samba_share_writable: "yes"
    variable: "[WORKGROUP]"
    
  tasks:
  - name: Install samba
    yum:
      name: samba
      state: present
      
  - name: Create Samba Share Directory
    file:
      path: "{{ samba_share_path }}"
      state: directory
      mode: '0777'
      
  - name: Workgroup Insert
    lineinfile:
      path: /etc/samba/smb.conf
      line: "{{ variable }}"
      state: present
      
  - name: Configure Samba Share
    lineinfile:
      path: /etc/samba/smb.conf
      line: "{{ item }}"
      create: yes
      insertafter: '[WORKGROUP]'
    with_items:
      - "security = user"
      - "guest ok = {{ samba_share_guest_ok }}"
      - "writable = {{ samba_share_writable }}"
      - "create mask = 0660"
      - "directory mask = 0771"
      - "force user = nobody"
      - "force group = nogroup"
      - "valid users = 'fonok'"
      - "path = {{ samba_share_path }}"
      - "name = {{ samba_share_name }}"

  - name: Create Samba Group
    group:
      name: smbgroup
      state: present
      
  - name: Add user to Samba Group
    user:
      name: fonok
      groups: smbgroup
      append: yes
      